# +---------------------------------------------------------------------------+
# |                     AstraRedstoneSystems - Configuration file             |
# +---------------------------------------------------------------------------+


# =========================================
#             General Settings
# =========================================
settings:
  # Wybierz język pluginu (Dostępne: pl, en)
  # Select the plugin language (Available: pl, en)
  language: en

  # Should the plugin check for newer versions of the plugin?
  check-updates: true

  # Should logic gate state change and general debugging be sent?
  debug-mode: false