# +---------------------------------------------------------------------------+
# |                     AstraLogicGates - Configuration file                  |
# +---------------------------------------------------------------------------+

# ===============================
#          MAIN SETTINGS
# ===============================

# DO NOT change this value
config-version: 1.1.0

# Wybierz język pluginu (Dostępne: pl, en)
# Select the plugin language (Available: pl, en)
language: pl

# Should the plugin check for newer versions of the plugin?
check-updates: true

# Should debugging be enabled in logic gates?
debug-mode: false