name: AstraRedstoneSystems
version: '${version}'
main: pl.dawcou.astrars.AstraRS
api-version: '1.18'
load: POSTWORLD
author: DawcoU

commands:
  bramka:
    aliases: [gate]
  astraredstonesystems:
    aliases: [ars]

permissions:
  astrars.gates:
    description: Pozwala używać komendy /bramka
    default: op
  astrars.admin:
    description: Pozwala używać komendy /alg link
    default: op
  astrars.update:
    description: Wyświetla powiadomenia o nowej wersji
    default: op
  astrars.reload:
    description: Pozwala używać komendy /ars reload
    default: op

  astrars.gates.*:
    default: op

  astrars.gates.logic:
    default: op

  astrars.gates.memory:
    default: op

  astrars.gates.numbers:
    default: op

  astrars.gates.string:
    default: op

  astrars.gates.data:
    default: op

  astrars.gates.space:
    default: op

  astrars.gates.time:
    default: op
