name: AstraRedstoneSystems
version: '${version}'

main: pl.dawcou.AstraRedstoneSystems.AstraRS
api-version: '1.20'
load: POSTWORLD
commands:
  bramka:
    description: Komenda do brania bramek logicznych
    aliases: [gate, logicgate, bramkalogiczna]
  astraredstonesystems:
    description: Główna komenda pluginu
    aliases: [ars]

permissions:
  astrars.gates:
    description: Pozwala używać komendy /bramka
    default: op
  astrars.admin:
    description: Pozwala używać komendy /alg link
    default: op
  astrars.update:
    description: Wyświetla powiadomenia o nowej wersji
    default: op
  astrars.reload:
    description: Pozwala używać komendy /ars reload
    default: op
