name: AstraLogicGates
version: '${version}'

main: pl.dawcou.AstraLogicGates.AstraLogicGates
api-version: '1.18'
load: POSTWORLD
commands:
  bramka:
    description: Komenda do brania bramek logicznych
    aliases: [gate, logicgate, bramkalogiczna]
  astralogicgates:
    description: Główna komenda pluginu
    aliases: [alg]

permissions:
  astralogicgates.gates:
    description: Pozwala używać komendy /bramka
    default: op
  astralogicgates.admin:
    description: Pozwala używać komendy /alg link
    default: op
  astralogicgates.reload:
    description: Pozwala używać komendy /astralogicgates reload
    default: op
